name: 批量生成并发布语言包

on:
  workflow_dispatch: # 手动触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1：检出仓库代码
      - name: 检出仓库代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整的 git 历史记录

      # 步骤 2：设置 Git 用户信息
      - name: 设置 Git 用户信息
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 步骤 3：安装依赖
      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext zip jq

      # 步骤 4：为脚本赋予执行权限
      - name: 为脚本赋予执行权限
        run: chmod +x ./get_versions.sh ./process_versions.sh ./build.sh

      # 步骤 5：获取最近十个版本
      - name: 获取最近十个版本
        run: ./get_versions.sh

      # 步骤 6：生成语言包并创建 Release
      - name: 生成语言包并创建 Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: ./process_versions.sh
