name: 生成并发布语言包

on:
  schedule:
    - cron: "0 0 * * *" # 每天UTC时间凌晨0点运行
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整的 git 历史记录

      - name: 设置 Git 用户信息
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext zip jq

      - name: 为脚本赋予执行权限
        run: chmod +x ./get_new_versions.sh ./process_versions.sh ./build.sh

      - name: 获取新版本
        id: get_new_versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: ./get_new_versions.sh

      - name: 处理新版本
        if: steps.get_new_versions.outputs.has_new_versions == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: ./process_versions.sh
